### PR TITLE
Create sql2json.py

### PR DESCRIPTION
**Pull request by savamarius**
I modify the script from utils and get new one which take all information about a connection and put in json format. The old is still good because get all information about a connection and related connections.

### CODE REVIEW

**Comment by phibos** [comment]
Thanks for your contribution. What is the json output used for?

**Comment by savamarius** [comment]
This is the output template of json is:
[{"local_host": "", "fingerprints": [], "resolve_hostname": null, "dcerpcrequests": [], "connection_timestamp": "", "connection_type": "reject", "connection_protocol": "", "p0fs": [], "local_port": "", "commands_mssql": [], "dcerpcbinds": [], "remote_hostname": "", "commands_mysql": [], "logins": [], "connection": "", "emu_services": [], "sip_commands": [], "resolve_result": "", "connection_root": "", "downloads": [], "connection_parent": "", "offers": [], "resolve": "", "remote_port": "", "profiles": [], "connection_transport": "tcp", "resolve_type": "", "remote_host": ""}]

**Comment by savamarius** [comment]
And the sintax for the command is python script.py inputpath.sql outpath.json + additional parameters if you want to select only some information from database.

**Comment by phibos** [comment]
I have tested your script and it works as described. But there is already an ihandler that can write information about an attack/connection encoded as json to a file. So why should I use your script? Are there any advantages?

**Comment by savamarius** [comment]
The ihandler for json doesn't write all information about one connection. That is the reason for which i had write this script. When the ihandler for json will work properly, then this script will become useless.

**Comment by phibos** [comment]
I'm sorry but this pull request will not be merged for the following reasons:

* it is not compatible with the current json logger, see #3 for more information about the output format
* it uses Python 2.x
* there is no documentation
* the format of commit message does not comply with the other messages

**Pull request closed without merging**
