### PR TITLE
Add SHA256 utility function

### PR DESCRIPTION
**Pull request by JesseBowling**
##### ISSUE TYPE
 - Feature

##### SUMMARY
This adds a new function in the utils library to calculate the SHA256 hash for a file, using the same logic as existing functions for MD5 and SHA512 

I propose this addition as there are libraries of hashes that do not support SHA512 hashes, while SHA256 hashes are supported. Generally, my experience has been that SHA256 hashes are more widely used for malware identification, etc.

Inclusion of the function here would allow individual output modules the option of using this hash algorithm, without requiring any changes to existing code.

### CODE REVIEW

**Comment by JesseBowling** [comment]
Anyone available to review this?

**Comment by JesseBowling** [comment]
Is the dionaea project abandoned?

**Comment by ZeNiRe** [comment]
> Is the dionaea project abandoned?

Seems to be. I have replaced dionaea.

**Comment by phibos** [comment]
> Is the dionaea project abandoned?

Would be great if just a few people would help in reviewing the merge requests and respond with a :+1: or a short comment.

**Comment by phibos** [comment]
> > Is the dionaea project abandoned?
> 
> Seems to be. I have replaced dionaea.

@ZeNiRe Would be of interest to me if people are still running dionaea after all this years or if I should discontinue the project and spend my time on other open source projects.

**Comment by JesseBowling** [comment]
Anecdotally, there are plenty of people still using Dionaea (thanks by the way!). We have it integrated into our project as one of the honeypots:

https://communityhoneynetwork.readthedocs.io/en/stable/dionaea/

Hope you didn't take offense to the question of currency. I would like to help out with maintaining the project as I'm able. Honestly much of the codebase is outside my experience, but I could certainly potentialy help triage PR's/issues, if I understood what would help you.

Happy to continue this conversation here, or Gitter/email/etc.

**Comment by ZeNiRe** [comment]
> > > Is the dionaea project abandoned?
> > 
> > 
> > Seems to be. I have replaced dionaea.
> 
> @ZeNiRe Would be of interest to me if people are still running dionaea after all this years or if I should discontinue the project and spend my time on other open source projects.

Would still love to continue with Dionaea and help improving it!

**Pull request merged**
