### PR TITLE
Adds printer support - fixes #245

### LINKED ISSUE #245: Printer support (PCL/PJL)
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I wrote a [printer honeypot](https://github.com/michaelneu/pjl-honeypot), which I could integrate into dionaea over the holiday season. Would you be interested in such a honeypot?

We're running honeypots in a university course to collect and analyze malware. From our stats, printers are by far not as attractive targets to attackers as e.g. SMB, but we still receive some prints since the rise of "printer advertising". By integrating my honeypot into dionaea, a wider audience would be able to receive and analyze "attacks" against printers by simply adjusting their dionaea config.

##### EXPECTED RESULTS
Receive prints not meant for the public (wrong printer setup), monitor attacks from e.g. PRET, or to get a laughter here and there, when somebody prints a page about "serpent people in New York" (most likely outcome).

### PR DESCRIPTION
**Pull request by michaelneu**
##### ISSUE TYPE
 - Feature

##### SUMMARY

As discussed in #245, this PR adds support for PJL/PCL:

- Most messages can be overridden using the `pjl_msgs` field in the config, by specifying the corresponding key from the `pjl_default_responses` dictionary
- Printed files are stored in `dionaea.download.dir`. Using the default config, that's `var/lib/binaries`
- Multiple volumes can be created in the `root` directory by creating e.g. the directories `{0,1}/foo`. Both volume 0 and 1 will have a "foo" directory. To have a consistent volume behaviour, the `info_filesys` message needs to be overridden accordingly.
- Documentation is included. I linked the code reference to this repository already, so until this PR is merged, it'll 404.

Tested using PRET and printing files using the macOS built-in PCL driver.

If you want to convert the printed PCL files to PDF, you may want to check out [GhostPCL Docker image](https://github.com/michaelneu/ghostpcl-docker).

Lastly: I'd be happy to further maintain this module, if you want.

### CODE REVIEW

**Comment by phibos** [comment]
test this please

**Comment by michaelneu** [comment]
I've added some tests, similar to the others in the `tests` directory. Please let me know if there's anything missing or whether there are any changes required.

**Comment by phibos** [comment]
test this please

**Comment by phibos** [comment]
Thanks for your work. I have deployed your code to one of my test nodes and run your tests and I was able to capture the pcl file. I will deploy it to some of my other nodes and try to capture some real world and examples.

**Comment by phibos** [comment]
The main reason why I haven't merged this request is a licensing issue.

Most of the dionaea components use the GPLv2+. The pyev packages is licensed under the GPLv3+(will remove this in the near future), parts of the TFTP service are licensed under the CNRI Python License (incompatible with GPL) and parts of the ftp service are licensed under the MIT (compatible with GPL).

The file printer.py has a GPLv2+ header but most of the parts are based on the work of a project licensed under MIT. Should/Can we mix licenses in this way? Would it be better to relicense the code under the GPLv2+ or to change license of the printer module to MIT? Would SPDX or FOSSology simplify the process?

**Comment by phibos** [comment]
Can you please rebase and repush your code to resolve the merge conflicts and to rerun the CI pipeline.

**Comment by phibos** [comment]
@michaelneu To fix some minor issues I had to create a new branch and a new PR. Feel free to have a look at #301 . I'm closing this PR in favour of the new one.

**Pull request closed without merging**
